site_name: Orb Aggregation Framework (OAF)
theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - Tooling Evaluation: tooling_evaluation.md
plugins:
  - search